// README
// DO NOT EDIT THIS FILE
// Beautiful Goose generates this file automatically during publishing

export default {
  toc: [
    {
      type: `doc`,
      id: `index`,
    },
    {
      type: `category`,
      label: `Privacy and personal data collection disclosure`,
      link: {
        type: `doc`,
        id: `ppdcd-trend-vision-one`,
      },
      items: [
        {
          type: `doc`,
          id: `pre-release-disclaimer`,
        },
        {
          type: `doc`,
          id: `pre-release-sub-feature-disclaimer`,
        },
      ],
    },
    {
      type: `doc`,
      id: `data-privacy-security-compliance`,
    },
    {
      type: `doc`,
      id: `pci-security-standards`,
    },
    {
      type: `category`,
      label: `Introduction`,
      link: {
        type: `doc`,
        id: `introduction-part-trend-vision-one`,
      },
      items: [
        {
          type: `category`,
          label: `Trend Vision One`,
          link: {
            type: `doc`,
            id: `trend-Vision-One-About`,
          },
          items: [
            {
              type: `doc`,
              id: `features-benefits-trend-vision-one`,
            },
            {
              type: `doc`,
              id: `supported-products`,
            },
            {
              type: `doc`,
              id: `platform-directory`,
            },
            {
              type: `doc`,
              id: `account-info-settings`,
            },
            {
              type: `doc`,
              id: `account-settings-foundation`,
            },
            {
              type: `doc`,
              id: `user-account-switch`,
            },
            {
              type: `doc`,
              id: `business-profile`,
            },
            {
              type: `category`,
              label: `Context menu`,
              link: {
                type: `doc`,
                id: `context-menu`,
              },
              items: [
                {
                  type: `doc`,
                  id: `advanced-analysis-actions-intro`,
                },
                {
                  type: `doc`,
                  id: `response-actions-intro`,
                },
                {
                  type: `doc`,
                  id: `search-actions`,
                },
                {
                  type: `doc`,
                  id: `display-settings-actions`,
                },
              ],
            },
            {
              type: `category`,
              label: `Simulations`,
              link: {
                type: `doc`,
                id: `simulations`,
              },
              items: [
                {
                  type: `doc`,
                  id: `running-simulations-endpoints-xdr`,
                },
                {
                  type: `doc`,
                  id: `simulations-endpoint-sensor`,
                },
                {
                  type: `doc`,
                  id: `simulations-deep-security-agents`,
                },
                {
                  type: `doc`,
                  id: `network-sensor-attack-simulation`,
                },
                {
                  type: `doc`,
                  id: `tippingpoint-network-attack-sim`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Trend Vision One Mobile`,
          link: {
            type: `doc`,
            id: `trend-vision-one-mobile`,
          },
          items: [
            {
              type: `doc`,
              id: `get-start-mobile`,
            },
            {
              type: `doc`,
              id: `receive-notifications-console`,
            },
          ],
        },
        {
          type: `category`,
          label: `Checking the Trend Vision One service status`,
          link: {
            type: `doc`,
            id: `checking-service-status`,
          },
          items: [
            {
              type: `doc`,
              id: `service-level-objectives`,
            },
          ],
        },
      ],
    },
    {
      type: `category`,
      label: `Getting started`,
      link: {
        type: `doc`,
        id: `getting-started-part`,
      },
      items: [
        {
          type: `category`,
          label: `Getting started with Trend Vision One`,
          link: {
            type: `doc`,
            id: `getting-started-trend-vision`,
          },
          items: [
            {
              type: `category`,
              label: `Accessing your Trend Vision One console`,
              link: {
                type: `doc`,
                id: `accessing-your-console`,
              },
              items: [
                {
                  type: `category`,
                  label: `Essential Access`,
                  link: {
                    type: `doc`,
                    id: `essential-access`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `activating-essential-access`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Advanced Access`,
                  link: {
                    type: `doc`,
                    id: `advanced-access`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `activating-advanced-access`,
                    },
                  ],
                },
              ],
            },
            {
              type: `category`,
              label: `Updating Trend Vision One to the Foundation Services release`,
              link: {
                type: `doc`,
                id: `update-foundation-services-release`,
              },
              items: [
                {
                  type: `doc`,
                  id: `foundation-update-consider`,
                },
                {
                  type: `doc`,
                  id: `foundation-services-update-impacts`,
                },
              ],
            },
            {
              type: `doc`,
              id: `connecting-your-idp-solutions`,
            },
            {
              type: `category`,
              label: `Configuring user roles and accounts`,
              link: {
                type: `doc`,
                id: `configuring-user-roles-accounts`,
              },
              items: [
                {
                  type: `doc`,
                  id: `configuring-user-roles`,
                },
                {
                  type: `doc`,
                  id: `configuring-user-accounts`,
                },
              ],
            },
            {
              type: `category`,
              label: `Firewall exception requirements for Trend Vision One`,
              link: {
                type: `doc`,
                id: `firewall-exception-requirements-for`,
              },
              items: [
                {
                  type: `category`,
                  label: `Americas - firewall exceptions`,
                  link: {
                    type: `doc`,
                    id: `americas-firewall-exceptions`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `firewall-americas-all-exceptions`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-americas-cloud-service`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-americas-hosted-service`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Australia - firewall exceptions`,
                  link: {
                    type: `doc`,
                    id: `australia-firewall-exceptions`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `firewall-australia-all-exceptions`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-australia-cloud-service`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-australia-hosted-service`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Europe - firewall exceptions`,
                  link: {
                    type: `doc`,
                    id: `europe-firewall-exceptions-part`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `firewall-europe-all-exceptions`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-europe-cloud-service`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-europe-hosted-service`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `India - firewall exceptions`,
                  link: {
                    type: `doc`,
                    id: `india-firewall-exceptions-section`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `firewall-india-all-exceptions`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-india-cloud-service`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-india-hosted-service`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Japan - firewall exceptions`,
                  link: {
                    type: `doc`,
                    id: `japan-firewall-exceptions-section`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `firewall-japan-all-exceptions`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-japan-cloud-service`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-japan-hosted-service`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Singapore - firewall exceptions`,
                  link: {
                    type: `doc`,
                    id: `singapore-firewall-section`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `firewall-singapore-all-global`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-singapore-cloud-service`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-singapore-hosted-service`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Middle East and Africa - firewall exceptions`,
                  link: {
                    type: `doc`,
                    id: `uae-firewall-exceptions`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `firewall-uae-all-exceptions`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-uae-cloud-service`,
                    },
                    {
                      type: `doc`,
                      id: `firewall-uae-hosted-service`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Legacy firewall exceptions`,
                  link: {
                    type: `doc`,
                    id: `legacy-firewall-exceptions`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `australia-firewall-exception-list`,
                    },
                    {
                      type: `doc`,
                      id: `europe-firewall-exceptions`,
                    },
                    {
                      type: `doc`,
                      id: `india-firewall-exceptions`,
                    },
                    {
                      type: `doc`,
                      id: `united-states-firewall-exceptions`,
                    },
                  ],
                },
              ],
            },
            {
              type: `doc`,
              id: `existing-products-instance`,
            },
            {
              type: `doc`,
              id: `reviewing-detection-models`,
            },
            {
              type: `doc`,
              id: `checking-workbench-alerts`,
            },
          ],
        },
      ],
    },
    {
      type: `category`,
      label: `Dashboards and Reports`,
      link: {
        type: `doc`,
        id: `dashboards-reports`,
      },
      items: [
        {
          type: `category`,
          label: `Security Dashboard`,
          link: {
            type: `doc`,
            id: `security-dashboard`,
          },
          items: [
            {
              type: `doc`,
              id: `customizing-security-dashboard`,
            },
            {
              type: `doc`,
              id: `protocol-traffic-summary-widget`,
            },
          ],
        },
      ],
    },
    {
      type: `category`,
      label: `XDR Threat Investigation`,
      link: {
        type: `doc`,
        id: `xdr-threat-investigation`,
      },
      items: [
        {
          type: `category`,
          label: `Detection Model Management`,
          link: {
            type: `doc`,
            id: `detection-model-management`,
          },
          items: [
            {
              type: `category`,
              label: `Detection models`,
              link: {
                type: `doc`,
                id: `detection-models`,
              },
              items: [
                {
                  type: `doc`,
                  id: `detection-model-data`,
                },
              ],
            },
            {
              type: `category`,
              label: `Custom models`,
              link: {
                type: `doc`,
                id: `custom-models`,
              },
              items: [
                {
                  type: `doc`,
                  id: `custom-model-data`,
                },
                {
                  type: `doc`,
                  id: `configuring-custom-model`,
                },
              ],
            },
            {
              type: `category`,
              label: `Custom filters`,
              link: {
                type: `doc`,
                id: `custom-filters`,
              },
              items: [
                {
                  type: `doc`,
                  id: `creating-custom-filter`,
                },
                {
                  type: `doc`,
                  id: `custom-filter-query-format`,
                },
                {
                  type: `doc`,
                  id: `custom-filter-data`,
                },
                {
                  type: `category`,
                  label: `Trend Micro Sigma specification`,
                  link: {
                    type: `doc`,
                    id: `trend-micro-sigma-specification`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `general-guidelines`,
                    },
                    {
                      type: `doc`,
                      id: `structure`,
                    },
                    {
                      type: `doc`,
                      id: `available-data-subtypes`,
                    },
                    {
                      type: `doc`,
                      id: `search-identifier-element`,
                    },
                    {
                      type: `doc`,
                      id: `using-regex-custom-filters`,
                    },
                  ],
                },
              ],
            },
            {
              type: `category`,
              label: `Exceptions`,
              link: {
                type: `doc`,
                id: `exceptions`,
              },
              items: [
                {
                  type: `doc`,
                  id: `adding-custom-exception`,
                },
                {
                  type: `doc`,
                  id: `adding-exception-context-menu`,
                },
                {
                  type: `doc`,
                  id: `editing-custom-exception`,
                },
              ],
            },
            {
              type: `doc`,
              id: `models-filters-email-collab-data`,
            },
          ],
        },
        {
          type: `category`,
          label: `Workbench`,
          link: {
            type: `doc`,
            id: `workbench`,
          },
          items: [
            {
              type: `category`,
              label: `Workbench Insights`,
              link: {
                type: `doc`,
                id: `workbench-insights`,
              },
              items: [
                {
                  type: `category`,
                  label: `Workbench insight details`,
                  link: {
                    type: `doc`,
                    id: `workbench-insight-details`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `alerts-workbench-insights`,
                    },
                    {
                      type: `doc`,
                      id: `insight-based-execution-profile`,
                    },
                  ],
                },
                {
                  type: `doc`,
                  id: `assigning-insights`,
                },
              ],
            },
            {
              type: `category`,
              label: `All Alerts`,
              link: {
                type: `doc`,
                id: `all-alerts`,
              },
              items: [
                {
                  type: `doc`,
                  id: `alert-details`,
                },
                {
                  type: `category`,
                  label: `Investigate an alert`,
                  link: {
                    type: `doc`,
                    id: `investigating-alert`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `context-menu-2`,
                    },
                    {
                      type: `category`,
                      label: `Advanced Analysis actions`,
                      link: {
                        type: `doc`,
                        id: `advanced-analysis-actions`,
                      },
                      items: [
                        {
                          type: `category`,
                          label: `Execution Profile`,
                          link: {
                            type: `doc`,
                            id: `execution-profile`,
                          },
                          items: [
                            {
                              type: `doc`,
                              id: `enabling-webgl`,
                            },
                          ],
                        },
                        {
                          type: `category`,
                          label: `Network analytics report`,
                          link: {
                            type: `doc`,
                            id: `network-analytics-report`,
                          },
                          items: [
                            {
                              type: `doc`,
                              id: `overview-network-analytics-report`,
                            },
                            {
                              type: `doc`,
                              id: `reviewing-summary`,
                            },
                            {
                              type: `category`,
                              label: `Analysis using the Correlation Graph`,
                              link: {
                                type: `doc`,
                                id: `analysis-using-correlation-graph`,
                              },
                              items: [
                                {
                                  type: `doc`,
                                  id: `correlation-graph-advanced-search`,
                                },
                              ],
                            },
                            {
                              type: `doc`,
                              id: `analysis-transaction-ioc-details`,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  type: `doc`,
                  id: `adding-exception-context-menu-2`,
                },
                {
                  type: `doc`,
                  id: `assigning-alerts`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Search app`,
          link: {
            type: `doc`,
            id: `search-app`,
          },
          items: [
            {
              type: `doc`,
              id: `executing-threat-hunting-queries`,
            },
            {
              type: `doc`,
              id: `search-actions-context-menu`,
            },
            {
              type: `category`,
              label: `Search syntax`,
              link: {
                type: `doc`,
                id: `search-syntax`,
              },
              items: [
                {
                  type: `doc`,
                  id: `using-regex-search-queries`,
                },
              ],
            },
            {
              type: `doc`,
              id: `saved-queries`,
            },
            {
              type: `category`,
              label: `Search results`,
              link: {
                type: `doc`,
                id: `search-results`,
              },
              items: [
                {
                  type: `doc`,
                  id: `custom-view-search-results`,
                },
              ],
            },
            {
              type: `category`,
              label: `Search method data sources`,
              link: {
                type: `doc`,
                id: `search-method-data-sources`,
              },
              items: [
                {
                  type: `doc`,
                  id: `general-search`,
                },
                {
                  type: `doc`,
                  id: `detections`,
                },
                {
                  type: `category`,
                  label: `Endpoint activity data sources`,
                  link: {
                    type: `doc`,
                    id: `endpoint-activity-data`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `eventid-eventsubid-mapping`,
                    },
                  ],
                },
                {
                  type: `doc`,
                  id: `firewall-activity-data`,
                },
                {
                  type: `doc`,
                  id: `identity-access-activity-data`,
                },
                {
                  type: `doc`,
                  id: `network-activity-data`,
                },
                {
                  type: `doc`,
                  id: `third-party-logs-mapping`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Observed Attack Techniques`,
          link: {
            type: `doc`,
            id: `observed-attack-techniques`,
          },
          items: [
            {
              type: `category`,
              label: `Troubleshooting & FAQ`,
              link: {
                type: `doc`,
                id: `troubleshooting-faq`,
              },
              items: [
                {
                  type: `doc`,
                  id: `how-does-risk-level-event`,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: `category`,
      label: `Threat Intelligence`,
      link: {
        type: `doc`,
        id: `threat-intelligence`,
      },
      items: [
        {
          type: `category`,
          label: `Intelligence Reports`,
          link: {
            type: `doc`,
            id: `intelligence-reports`,
          },
          items: [
            {
              type: `doc`,
              id: `curated-intelligence`,
            },
            {
              type: `doc`,
              id: `custom-intelligence`,
            },
            {
              type: `doc`,
              id: `sweeping-types`,
            },
            {
              type: `doc`,
              id: `stix-indicator-patterns-sweep`,
            },
          ],
        },
        {
          type: `category`,
          label: `Suspicious Object Management`,
          link: {
            type: `doc`,
            id: `suspicious-object-management`,
          },
          items: [
            {
              type: `category`,
              label: `Suspicious Object List`,
              link: {
                type: `doc`,
                id: `suspicious-object-list`,
              },
              items: [
                {
                  type: `doc`,
                  id: `add-import-suspicious-objects`,
                },
                {
                  type: `doc`,
                  id: `suspicious-object-actions`,
                },
              ],
            },
            {
              type: `category`,
              label: `Exception list`,
              link: {
                type: `doc`,
                id: `exception-list`,
              },
              items: [
                {
                  type: `doc`,
                  id: `adding-exceptions`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Sandbox Analysis`,
          link: {
            type: `doc`,
            id: `sandbox-analysis`,
          },
          items: [
            {
              type: `doc`,
              id: `consolidated-analysis-results`,
            },
            {
              type: `doc`,
              id: `submitting-objects-for-analysis`,
            },
            {
              type: `doc`,
              id: `submission-settings`,
            },
            {
              type: `doc`,
              id: `supported-file-types`,
            },
            {
              type: `doc`,
              id: `reasons-for-analysis-failure`,
            },
          ],
        },
      ],
    },
    {
      type: `category`,
      label: `Workflow and Automation`,
      link: {
        type: `doc`,
        id: `workflow-automation`,
      },
      items: [
        {
          type: `category`,
          label: `Case Management`,
          link: {
            type: `doc`,
            id: `case-management`,
          },
          items: [
            {
              type: `category`,
              label: `Trend Vision One cases`,
              link: {
                type: `doc`,
                id: `trend-vision-one-cases`,
              },
              items: [
                {
                  type: `doc`,
                  id: `configure-ticket-profiles`,
                },
              ],
            },
            {
              type: `doc`,
              id: `case-viewer`,
            },
            {
              type: `category`,
              label: `Troubleshooting and FAQs`,
              link: {
                type: `doc`,
                id: `cm-troubleshooting-faqs`,
              },
              items: [
                {
                  type: `doc`,
                  id: `case-management-faq`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Security Playbooks`,
          link: {
            type: `doc`,
            id: `security-playbooks`,
          },
          items: [
            {
              type: `doc`,
              id: `security-playbooks-requirements`,
            },
            {
              type: `category`,
              label: `Execution results`,
              link: {
                type: `doc`,
                id: `execution-results`,
              },
              items: [
                {
                  type: `category`,
                  label: `Execution details`,
                  link: {
                    type: `doc`,
                    id: `execution-details`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `action-details`,
                    },
                  ],
                },
              ],
            },
            {
              type: `category`,
              label: `User-defined playbooks`,
              link: {
                type: `doc`,
                id: `user-defined-playbooks`,
              },
              items: [
                {
                  type: `doc`,
                  id: `create-automated-response-playbooks`,
                },
                {
                  type: `doc`,
                  id: `create-endpoint-response-playbooks`,
                },
              ],
            },
            {
              type: `doc`,
              id: `template-based-playbooks`,
            },
            {
              type: `doc`,
              id: `playbook-nodes`,
            },
          ],
        },
        {
          type: `category`,
          label: `Response Management`,
          link: {
            type: `doc`,
            id: `response-management`,
          },
          items: [
            {
              type: `category`,
              label: `Response actions`,
              link: {
                type: `doc`,
                id: `response-actions-section`,
              },
              items: [
                {
                  type: `doc`,
                  id: `add-block-list-task`,
                },
                {
                  type: `doc`,
                  id: `collect-file-task`,
                },
                {
                  type: `doc`,
                  id: `collect-network-analysis-package`,
                },
                {
                  type: `doc`,
                  id: `disable-user-account-task`,
                },
                {
                  type: `doc`,
                  id: `enable-user-account-task`,
                },
                {
                  type: `doc`,
                  id: `force-password-reset-task`,
                },
                {
                  type: `doc`,
                  id: `isolate-endpoint-task`,
                },
                {
                  type: `doc`,
                  id: `remove-block-list-task`,
                },
                {
                  type: `doc`,
                  id: `restore-connection-task`,
                },
                {
                  type: `category`,
                  label: `Run Remote Custom Script task`,
                  link: {
                    type: `doc`,
                    id: `run-remote-custom-script-task`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `sample-signed-powershell-script`,
                    },
                  ],
                },
                {
                  type: `doc`,
                  id: `scan-for-malware-task`,
                },
                {
                  type: `category`,
                  label: `Start Remote Shell Session task`,
                  link: {
                    type: `doc`,
                    id: `start-remote-shell-session-task`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `remote-shell-windows-endpoints`,
                    },
                    {
                      type: `doc`,
                      id: `remote-shell-linux-endpoints`,
                    },
                    {
                      type: `doc`,
                      id: `remote-shell-mac-endpoints`,
                    },
                  ],
                },
                {
                  type: `doc`,
                  id: `submit-for-sandbox-analysis-task`,
                },
                {
                  type: `doc`,
                  id: `terminate-process-task`,
                },
              ],
            },
            {
              type: `doc`,
              id: `response-data`,
            },
            {
              type: `category`,
              label: `Response Management settings`,
              link: {
                type: `doc`,
                id: `response-management-settings`,
              },
              items: [
                {
                  type: `doc`,
                  id: `allow-traffic-isolated-endpoints`,
                },
                {
                  type: `doc`,
                  id: `response-exclude-endpoints`,
                },
                {
                  type: `doc`,
                  id: `time-out-settings`,
                },
                {
                  type: `doc`,
                  id: `approval-specified-actions`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Third-Party Integration`,
          link: {
            type: `doc`,
            id: `third-party-integration`,
          },
          items: [
            {
              type: `category`,
              label: `Active Directory (on-premises) integration`,
              link: {
                type: `doc`,
                id: `ad-premises-integration`,
              },
              items: [
                {
                  type: `doc`,
                  id: `ad-data-usage-associated-apps`,
                },
                {
                  type: `category`,
                  label: `Configuring data synchronization and user access control`,
                  link: {
                    type: `doc`,
                    id: `adfs-user-access-control`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `active-directory-permissions`,
                    },
                  ],
                },
                {
                  type: `doc`,
                  id: `security-event-forwarding`,
                },
              ],
            },
            {
              type: `doc`,
              id: `asrm-splunk-integration`,
            },
            {
              type: `doc`,
              id: `attackiq-bas-integration`,
            },
            {
              type: `doc`,
              id: `check-point-opsec-integration`,
            },
            {
              type: `doc`,
              id: `chronicle-soar-integration`,
            },
            {
              type: `doc`,
              id: `cisco-xdr-integration`,
            },
            {
              type: `doc`,
              id: `medigate-integration`,
            },
            {
              type: `doc`,
              id: `cloud-pak-for-security-integration`,
            },
            {
              type: `category`,
              label: `Cortex XSOAR integration`,
              link: {
                type: `doc`,
                id: `cortex-xsoar-integration`,
              },
              items: [
                {
                  type: `doc`,
                  id: `user-role-cortex-xsoar`,
                },
              ],
            },
            {
              type: `doc`,
              id: `cyborg-security-hunter-integration`,
            },
            {
              type: `doc`,
              id: `cymulate-integration`,
            },
            {
              type: `doc`,
              id: `d3-security-integration`,
            },
            {
              type: `doc`,
              id: `elastic-integration`,
            },
            {
              type: `doc`,
              id: `fortigate-ng-firewall`,
            },
            {
              type: `doc`,
              id: `greenbone-integration`,
            },
            {
              type: `category`,
              label: `Google Cloud Identity integration`,
              link: {
                type: `doc`,
                id: `identity-integration-gcp`,
              },
              items: [
                {
                  type: `doc`,
                  id: `access-permissions-google-cloud-id`,
                },
                {
                  type: `doc`,
                  id: `gcp-id-usage-associated-apps`,
                },
                {
                  type: `doc`,
                  id: `gcp-identity-integration`,
                },
                {
                  type: `doc`,
                  id: `revoking-gcp-id-permissions`,
                },
              ],
            },
            {
              type: `doc`,
              id: `ibm-soar-integration`,
            },
            {
              type: `doc`,
              id: `jira-service-management-integration`,
            },
            {
              type: `doc`,
              id: `logpoint-siem-integration`,
            },
            {
              type: `doc`,
              id: `logpoint-soar-integration`,
            },
            {
              type: `doc`,
              id: `logrhythm-siem-integration`,
            },
            {
              type: `category`,
              label: `Microsoft Entra ID integration`,
              link: {
                type: `doc`,
                id: `integration-aad-third-party`,
              },
              items: [
                {
                  type: `doc`,
                  id: `access-permissions-data`,
                },
                {
                  type: `doc`,
                  id: `data-usage-associated-apps`,
                },
                {
                  type: `doc`,
                  id: `configuring-integration`,
                },
                {
                  type: `doc`,
                  id: `blocking-permissions`,
                },
                {
                  type: `doc`,
                  id: `assigning-password-admin-role`,
                },
                {
                  type: `doc`,
                  id: `troubleshooting-connections`,
                },
              ],
            },
            {
              type: `doc`,
              id: `microsoft-power-bi-integration`,
            },
            {
              type: `category`,
              label: `Microsoft Sentinel integration`,
              link: {
                type: `doc`,
                id: `microsoft-sentinel-integration`,
              },
              items: [
                {
                  type: `doc`,
                  id: `deploying-connector`,
                },
                {
                  type: `doc`,
                  id: `ingested-log-analytics-workspaces`,
                },
              ],
            },
            {
              type: `doc`,
              id: `misp-integration`,
            },
            {
              type: `doc`,
              id: `misp-integration-direct-connect`,
            },
            {
              type: `doc`,
              id: `nessus-pro-integration`,
            },
            {
              type: `doc`,
              id: `netskope-cte-integration`,
            },
            {
              type: `category`,
              label: `Okta integration`,
              link: {
                type: `doc`,
                id: `okta-integration`,
              },
              items: [
                {
                  type: `doc`,
                  id: `configuring-okta-tenants`,
                },
                {
                  type: `doc`,
                  id: `okta-url-api-token`,
                },
              ],
            },
            {
              type: `doc`,
              id: `openldap-integration`,
            },
            {
              type: `doc`,
              id: `palo-alto-panorama-integration`,
            },
            {
              type: `doc`,
              id: `picus-security-integration`,
            },
            {
              type: `doc`,
              id: `plain-text-free-integration`,
            },
            {
              type: `doc`,
              id: `proxysg-adv-secure-gateway`,
            },
            {
              type: `doc`,
              id: `qradar-cloud-stix-shifter`,
            },
            {
              type: `doc`,
              id: `qradar-xdr-integration`,
            },
            {
              type: `doc`,
              id: `qualys-integrate`,
            },
            {
              type: `doc`,
              id: `rapid7-insighttvm-integrate`,
            },
            {
              type: `doc`,
              id: `rapid7-nexpose-integration`,
            },
            {
              type: `doc`,
              id: `reliaquest-greymatter-integration`,
            },
            {
              type: `doc`,
              id: `rescana-integration`,
            },
            {
              type: `doc`,
              id: `safebreach-bas-integration`,
            },
            {
              type: `category`,
              label: `Salesforce integration`,
              link: {
                type: `doc`,
                id: `salesforce-integrate`,
              },
              items: [
                {
                  type: `doc`,
                  id: `salesforce-tennants`,
                },
              ],
            },
            {
              type: `doc`,
              id: `securonix-siem-integration`,
            },
            {
              type: `doc`,
              id: `servicenow-itsm-integration`,
            },
            {
              type: `category`,
              label: `ServiceNow ticketing system integration (for Security Playbooks and Case Management)`,
              link: {
                type: `doc`,
                id: `servicenow-ticket-system-playbook`,
              },
              items: [
                {
                  type: `doc`,
                  id: `config-case-management-ticket`,
                },
                {
                  type: `doc`,
                  id: `creating-ticket-profile`,
                },
              ],
            },
            {
              type: `doc`,
              id: `splunk-hec-connector-configuration`,
            },
            {
              type: `doc`,
              id: `splunk-soar-integration`,
            },
            {
              type: `doc`,
              id: `integration-splunk-addon`,
            },
            {
              type: `doc`,
              id: `syslog-connector-premises`,
            },
            {
              type: `doc`,
              id: `syslog-connector-saas`,
            },
            {
              type: `category`,
              label: `Syslog content mapping - CEF`,
              link: {
                type: `doc`,
                id: `syslog-content-mapping-cef`,
              },
              items: [
                {
                  type: `doc`,
                  id: `cef-workbench-logs`,
                },
                {
                  type: `doc`,
                  id: `cef-observed-attack-techniques-logs`,
                },
                {
                  type: `doc`,
                  id: `cef-account-audit-logs`,
                },
                {
                  type: `doc`,
                  id: `cef-system-audit-logs`,
                },
              ],
            },
            {
              type: `doc`,
              id: `taxii-feed-integration`,
            },
            {
              type: `doc`,
              id: `tanium-comply-integrate`,
            },
            {
              type: `doc`,
              id: `tenable-security-setup`,
            },
            {
              type: `doc`,
              id: `data-source-tenable-setup`,
            },
            {
              type: `doc`,
              id: `threatq-integration`,
            },
            {
              type: `doc`,
              id: `virustotal-integration`,
            },
            {
              type: `doc`,
              id: `vu-integration`,
            },
            {
              type: `doc`,
              id: `Zscaler-internet-access`,
            },
            {
              type: `doc`,
              id: `zscaler-private-access`,
            },
          ],
        },
        {
          type: `category`,
          label: `Service Gateway Management`,
          link: {
            type: `doc`,
            id: `service-gateway-management`,
          },
          items: [
            {
              type: `category`,
              label: `Getting started with Service Gateway`,
              link: {
                type: `doc`,
                id: `getting-started-service-gateway`,
              },
              items: [
                {
                  type: `doc`,
                  id: `service-gateway-overview`,
                },
                {
                  type: `doc`,
                  id: `whats-new-sg-management`,
                },
                {
                  type: `doc`,
                  id: `map-service-gateway-deployment`,
                },
                {
                  type: `category`,
                  label: `Service Gateway appliance system requirements`,
                  link: {
                    type: `doc`,
                    id: `sg-sys-requirements`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `sg-ports-used`,
                    },
                    {
                      type: `doc`,
                      id: `sizing-guide-sg-endpoints`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Deployment guides`,
                  link: {
                    type: `doc`,
                    id: `deployment-guides`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `sg-virtual-app-vmware-esxi`,
                    },
                    {
                      type: `doc`,
                      id: `deploy-virtual-appliance-ms-hyper-v`,
                    },
                    {
                      type: `doc`,
                      id: `sg-virtual-app-nutanix-ahv`,
                    },
                  ],
                },
              ],
            },
            {
              type: `category`,
              label: `Service Gateway appliance configuration`,
              link: {
                type: `doc`,
                id: `sg-appliance-configuration`,
              },
              items: [
                {
                  type: `category`,
                  label: `Managing services in Service Gateway`,
                  link: {
                    type: `doc`,
                    id: `managing-services-service-gateway`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `service-gateway-services`,
                    },
                    {
                      type: `doc`,
                      id: `activeupdate-configuration`,
                    },
                    {
                      type: `category`,
                      label: `Smart Protection Services`,
                      link: {
                        type: `doc`,
                        id: `smart-protection-services`,
                      },
                      items: [
                        {
                          type: `doc`,
                          id: `sps-product-support`,
                        },
                        {
                          type: `doc`,
                          id: `connect-smart-protection-server`,
                        },
                      ],
                    },
                    {
                      type: `category`,
                      label: `Forward Proxy Service`,
                      link: {
                        type: `doc`,
                        id: `forward-proxy-service`,
                      },
                      items: [
                        {
                          type: `doc`,
                          id: `predefined-allow-list`,
                        },
                      ],
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Configuring Service Gateway settings`,
                  link: {
                    type: `doc`,
                    id: `config-service-gateway-settings`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `snmp-defined-trap-messages`,
                    },
                  ],
                },
                {
                  type: `doc`,
                  id: `managing-service-gateway-storage`,
                },
                {
                  type: `doc`,
                  id: `create-sg-config-profile`,
                },
              ],
            },
            {
              type: `category`,
              label: `Service Gateway troubleshooting and FAQs`,
              link: {
                type: `doc`,
                id: `service-gateway-troubleshooting-faq`,
              },
              items: [
                {
                  type: `doc`,
                  id: `service-gateway-faqs`,
                },
                {
                  type: `category`,
                  label: `Troubleshooting Service Gateway`,
                  link: {
                    type: `doc`,
                    id: `troubleshooting-service-gateway`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `service-gateway-support-settings`,
                    },
                    {
                      type: `doc`,
                      id: `service-gateway-cli-commands`,
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: `category`,
      label: `Endpoint Security (for Standard Endpoint and Server & Workload Protection)`,
      link: {
        type: `doc`,
        id: `endpoint-security-for-sep-swp`,
      },
      items: [
        {
          type: `category`,
          label: `Getting Started with Trend Vision One Endpoint Security`,
          link: {
            type: `doc`,
            id: `get-start-endpoint-security`,
          },
          items: [
            {
              type: `doc`,
              id: `setup-endpoint-security-for-new`,
            },
            {
              type: `category`,
              label: `Deploy a Service Gateway and Configure Firewall Exceptions`,
              link: {
                type: `doc`,
                id: `deploy-service-gateway-exceptions`,
              },
              items: [
                {
                  type: `doc`,
                  id: `service-gateway-sys-req`,
                },
                {
                  type: `doc`,
                  id: `gateway-endpoint-sizing-guide`,
                },
                {
                  type: `doc`,
                  id: `deploy-service-gateway-vmware-esxi`,
                },
                {
                  type: `doc`,
                  id: `deploy-service-gateway-hyper-v`,
                },
              ],
            },
            {
              type: `category`,
              label: `Manage Your Agent Deployments`,
              link: {
                type: `doc`,
                id: `manage-your-agent-deployments`,
              },
              items: [
                {
                  type: `doc`,
                  id: `create-default-endpoint-policies`,
                },
                {
                  type: `category`,
                  label: `Deploy Agents`,
                  link: {
                    type: `doc`,
                    id: `deploy-agents`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `endpoint-sensor-agent-deployment`,
                    },
                    {
                      type: `category`,
                      label: `Using the Deployment Script`,
                      link: {
                        type: `doc`,
                        id: `using-endpoint-deployment-script`,
                      },
                      items: [
                        {
                          type: `doc`,
                          id: `troubleshooting-deployment-script`,
                        },
                      ],
                    },
                    {
                      type: `category`,
                      label: `Deployment using a golden image`,
                      link: {
                        type: `doc`,
                        id: `deployment-using-golden-image`,
                      },
                      items: [
                        {
                          type: `doc`,
                          id: `create-golden-agent-image`,
                        },
                        {
                          type: `doc`,
                          id: `updating-agent-for-templates`,
                        },
                      ],
                    },
                    {
                      type: `category`,
                      label: `Deploying Agents with a Software Management System`,
                      link: {
                        type: `doc`,
                        id: `deploy-agents-manage-system`,
                      },
                      items: [
                        {
                          type: `category`,
                          label: `Deploying Agents Using Microsoft Intune`,
                          link: {
                            type: `doc`,
                            id: `deploy-agents-ms-intune`,
                          },
                          items: [
                            {
                              type: `doc`,
                              id: `es-agent-deploy-intune`,
                            },
                          ],
                        },
                        {
                          type: `doc`,
                          id: `deploy-agents-using-sccm`,
                        },
                        {
                          type: `category`,
                          label: `Deploying Agents Using Group Policy Objects`,
                          link: {
                            type: `doc`,
                            id: `deploy-agents-gpo`,
                          },
                          items: [
                            {
                              type: `doc`,
                              id: `group-policy-object-sample-script`,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  type: `doc`,
                  id: `remove-endpoints`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Endpoint Inventory`,
          link: {
            type: `doc`,
            id: `endpoint-inventory-intro-part`,
          },
          items: [
            {
              type: `category`,
              label: `Endpoint Management`,
              link: {
                type: `doc`,
                id: `endpoint-management`,
              },
              items: [
                {
                  type: `doc`,
                  id: `sep-management`,
                },
                {
                  type: `doc`,
                  id: `swp-management`,
                },
                {
                  type: `doc`,
                  id: `connect-epp-management`,
                },
              ],
            },
            {
              type: `category`,
              label: `Global Settings`,
              link: {
                type: `doc`,
                id: `global-settings-endpoint-inventory`,
              },
              items: [
                {
                  type: `doc`,
                  id: `sensor-settings`,
                },
                {
                  type: `category`,
                  label: `Agent Installer Proxy Settings`,
                  link: {
                    type: `doc`,
                    id: `agent-installer-proxy-settings`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `configure-agent-installer-proxy`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Runtime Proxy Settings`,
                  link: {
                    type: `doc`,
                    id: `runtime-proxy-settings`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `configuring-runtime-proxy-policies`,
                    },
                    {
                      type: `doc`,
                      id: `runtime-proxy-priority-behavior`,
                    },
                  ],
                },
              ],
            },
            {
              type: `category`,
              label: `Endpoint Agent System Requirements`,
              link: {
                type: `doc`,
                id: `endpoint-agent-system-requirements`,
              },
              items: [
                {
                  type: `doc`,
                  id: `extended-support-for-agents`,
                },
                {
                  type: `doc`,
                  id: `es-agent-sys-reqs`,
                },
              ],
            },
            {
              type: `doc`,
              id: `endpoint-inventory-table-columns`,
            },
            {
              type: `doc`,
              id: `update-agent-virtual-desktops`,
            },
            {
              type: `category`,
              label: `Uninstalling Agents`,
              link: {
                type: `doc`,
                id: `uninstalling-agents`,
              },
              items: [
                {
                  type: `doc`,
                  id: `uninstall-windows-agents-tool`,
                },
                {
                  type: `doc`,
                  id: `uninstall-agents-intune`,
                },
                {
                  type: `doc`,
                  id: `uninstall-macos-agents-tool`,
                },
                {
                  type: `doc`,
                  id: `cleaning-up-uninstalled-agents`,
                },
              ],
            },
            {
              type: `category`,
              label: `Trend Vision One Endpoint Security Endpoint Inventory FAQ`,
              link: {
                type: `doc`,
                id: `endpoint-inventory-faq`,
              },
              items: [
                {
                  type: `doc`,
                  id: `endpoint-list-faq`,
                },
                {
                  type: `doc`,
                  id: `auto-disable-activity-monitoring`,
                },
                {
                  type: `doc`,
                  id: `removed-endpoint-reconnects-faq`,
                },
                {
                  type: `doc`,
                  id: `what-telemetry-collect-windows`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Endpoint Security Configuration`,
          link: {
            type: `doc`,
            id: `endpoint-security-configuration`,
          },
          items: [
            {
              type: `category`,
              label: `Endpoint Security Policies`,
              link: {
                type: `doc`,
                id: `sensor-settings-policies`,
              },
              items: [
                {
                  type: `doc`,
                  id: `about-endpoint-security-policies`,
                },
                {
                  type: `doc`,
                  id: `configuring-endpoint-policies`,
                },
                {
                  type: `doc`,
                  id: `sensor-monitoring-level`,
                },
                {
                  type: `doc`,
                  id: `network-content-inspection-engine`,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: `category`,
      label: `Network Security`,
      link: {
        type: `doc`,
        id: `network-security`,
      },
      items: [
        {
          type: `category`,
          label: `Getting started with Network Security`,
          link: {
            type: `doc`,
            id: `get-started-using-network-security`,
          },
          items: [
            {
              type: `category`,
              label: `Deep Discovery Inspector connection guides`,
              link: {
                type: `doc`,
                id: `ddi-connection-deployment`,
              },
              items: [
                {
                  type: `doc`,
                  id: `connecting-ddi-directly`,
                },
                {
                  type: `doc`,
                  id: `ddi-connect-service-gateway`,
                },
                {
                  type: `doc`,
                  id: `deploying-ddi-appliance-aws`,
                },
                {
                  type: `doc`,
                  id: `configuring-ddi-connections`,
                },
                {
                  type: `category`,
                  label: `Sandbox options for connected Deep Discovery Inspector appliances`,
                  link: {
                    type: `doc`,
                    id: `sandbox-deep-discovery-inspector`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `ddi-virtual-sandbox-aas`,
                    },
                  ],
                },
                {
                  type: `doc`,
                  id: `activate-ddi-clp`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Network Inventory`,
          link: {
            type: `doc`,
            id: `network-inventory`,
          },
          items: [
            {
              type: `category`,
              label: `Deep Discovery Inspector appliances`,
              link: {
                type: `doc`,
                id: `deep-discovery-inspector-appliances`,
              },
              items: [
                {
                  type: `doc`,
                  id: `appliance-details`,
                },
                {
                  type: `category`,
                  label: `Appliance Plans`,
                  link: {
                    type: `doc`,
                    id: `appliance-plans`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `plan-details`,
                    },
                    {
                      type: `doc`,
                      id: `creating-hotfix-critical-patch-plan`,
                    },
                    {
                      type: `doc`,
                      id: `creating-firmware-update-plan`,
                    },
                    {
                      type: `doc`,
                      id: `creating-replication-plan`,
                    },
                    {
                      type: `doc`,
                      id: `vai-deployment-plan`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Virtual Analyzer Image Source`,
                  link: {
                    type: `doc`,
                    id: `virtual-analyzer-image-source`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `va-config-image-source`,
                    },
                  ],
                },
                {
                  type: `doc`,
                  id: `ports-urls-used-ddi`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Network Analysis Configuration`,
          link: {
            type: `doc`,
            id: `network-analysis-configuration`,
          },
          items: [
            {
              type: `category`,
              label: `Monitoring and Scanning Network Traffic`,
              link: {
                type: `doc`,
                id: `monitoring-scanning-network-traffic`,
              },
              items: [
                {
                  type: `category`,
                  label: `Detection Exceptions`,
                  link: {
                    type: `doc`,
                    id: `detection-exceptions`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `configuring-detection-exceptions`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Packet Capture`,
                  link: {
                    type: `doc`,
                    id: `packet-capture`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `configuring-packet-capture`,
                    },
                  ],
                },
              ],
            },
            {
              type: `category`,
              label: `Network Resources`,
              link: {
                type: `doc`,
                id: `network-resources`,
              },
              items: [
                {
                  type: `doc`,
                  id: `network-resource-lists`,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: `category`,
      label: `Service Management`,
      link: {
        type: `doc`,
        id: `service-management`,
      },
      items: [
        {
          type: `category`,
          label: `Product Connector`,
          link: {
            type: `doc`,
            id: `product-connector`,
          },
          items: [
            {
              type: `doc`,
              id: `connecting-product`,
            },
            {
              type: `category`,
              label: `Required settings on supported products`,
              link: {
                type: `doc`,
                id: `req-setting-supported-product`,
              },
              items: [
                {
                  type: `doc`,
                  id: `connecting-apex-one-saas`,
                },
                {
                  type: `doc`,
                  id: `configuring-cloud-app-security`,
                },
                {
                  type: `doc`,
                  id: `configuring-deep-security-software`,
                },
                {
                  type: `doc`,
                  id: `configuring-txone-stellarone`,
                },
                {
                  type: `doc`,
                  id: `configuring-txone-edgeone`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Product Instance`,
          link: {
            type: `doc`,
            id: `product-instance`,
          },
          items: [
            {
              type: `category`,
              label: `Connecting existing products to Product Instance`,
              link: {
                type: `doc`,
                id: `connect-exist-prod-instance`,
              },
              items: [
                {
                  type: `doc`,
                  id: `configure-cloud-app-security`,
                },
                {
                  type: `doc`,
                  id: `configure-deep-security-software`,
                },
                {
                  type: `doc`,
                  id: `configuring-apex-one-onprem`,
                },
                {
                  type: `doc`,
                  id: `configure-trend-cloud-one`,
                },
                {
                  type: `doc`,
                  id: `configure-txone-stellarone`,
                },
                {
                  type: `doc`,
                  id: `configure-txone-edgeone`,
                },
              ],
            },
            {
              type: `doc`,
              id: `creating-new-product-instance`,
            },
            {
              type: `doc`,
              id: `creating-new-endpoint-group-manager`,
            },
          ],
        },
        {
          type: `category`,
          label: `Asset Visibility Management`,
          link: {
            type: `doc`,
            id: `asset-visibility-management`,
          },
          items: [
            {
              type: `doc`,
              id: `what-is-asset-visibility-management`,
            },
            {
              type: `doc`,
              id: `adding-asset-visibility-scope`,
            },
          ],
        },
        {
          type: `category`,
          label: `Asset Group Management`,
          link: {
            type: `doc`,
            id: `asset-group-management`,
          },
          items: [
            {
              type: `doc`,
              id: `creating-asset-group`,
            },
          ],
        },
      ],
    },
    {
      type: `category`,
      label: `Administration`,
      link: {
        type: `doc`,
        id: `administration-setting`,
      },
      items: [
        {
          type: `category`,
          label: `User Accounts, Identity Providers, and User Roles (Foundation Services release)`,
          link: {
            type: `doc`,
            id: `user-accounts-roles-idp-foundation`,
          },
          items: [
            {
              type: `category`,
              label: `User Roles (Foundation Services release)`,
              link: {
                type: `doc`,
                id: `user-roles-foundation-services`,
              },
              items: [
                {
                  type: `doc`,
                  id: `custom-user-roles-trend-vision-one`,
                },
                {
                  type: `doc`,
                  id: `predefined-roles-trend-vision-one`,
                },
              ],
            },
            {
              type: `category`,
              label: `User Accounts (Foundation Services release)`,
              link: {
                type: `doc`,
                id: `user-accounts-foundation-services`,
              },
              items: [
                {
                  type: `category`,
                  label: `Primary User Account`,
                  link: {
                    type: `doc`,
                    id: `primary-user-account`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `transfer-primary-account`,
                    },
                  ],
                },
                {
                  type: `category`,
                  label: `Configuring accounts`,
                  link: {
                    type: `doc`,
                    id: `configure-vision-accounts`,
                  },
                  items: [
                    {
                      type: `doc`,
                      id: `adding-saml-account`,
                    },
                    {
                      type: `doc`,
                      id: `adding-saml-group-account`,
                    },
                    {
                      type: `doc`,
                      id: `adding-idp-only-saml-group-account`,
                    },
                    {
                      type: `doc`,
                      id: `adding-a-local-account`,
                    },
                  ],
                },
                {
                  type: `doc`,
                  id: `enable-confige-mfa`,
                },
              ],
            },
            {
              type: `category`,
              label: `API Keys`,
              link: {
                type: `doc`,
                id: `platform-api-keys`,
              },
              items: [
                {
                  type: `doc`,
                  id: `api-keys-third-party-apps`,
                },
                {
                  type: `doc`,
                  id: `obtain-api-keys-third-party`,
                },
              ],
            },
            {
              type: `category`,
              label: `Identity Providers (Foundation Services release)`,
              link: {
                type: `doc`,
                id: `identity-providers`,
              },
              items: [
                {
                  type: `doc`,
                  id: `configuring-adfs`,
                },
                {
                  type: `doc`,
                  id: `config-google-cloud-saml`,
                },
                {
                  type: `doc`,
                  id: `configuring-saml-ad`,
                },
                {
                  type: `doc`,
                  id: `configuring-okta-saml`,
                },
                {
                  type: `doc`,
                  id: `configuring-onelogin`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Notifications`,
          link: {
            type: `doc`,
            id: `notifications`,
          },
          items: [
            {
              type: `doc`,
              id: `alert-notifications`,
            },
            {
              type: `doc`,
              id: `subscriptions-intro`,
            },
            {
              type: `doc`,
              id: `managing-webhooks`,
            },
            {
              type: `category`,
              label: `Configuring notifications`,
              link: {
                type: `doc`,
                id: `configure-admin-notifications`,
              },
              items: [
                {
                  type: `doc`,
                  id: `notifications-response-tasks`,
                },
                {
                  type: `doc`,
                  id: `notifications-workbench-alerts`,
                },
                {
                  type: `doc`,
                  id: `notification-private-access`,
                },
                {
                  type: `doc`,
                  id: `notifications-sg`,
                },
                {
                  type: `doc`,
                  id: `notifications-risk-event`,
                },
                {
                  type: `doc`,
                  id: `notification-case-update-summary`,
                },
                {
                  type: `doc`,
                  id: `notifications-case-update-for-owner`,
                },
                {
                  type: `doc`,
                  id: `notifications-new-assets`,
                },
              ],
            },
          ],
        },
        {
          type: `category`,
          label: `Audit Logs`,
          link: {
            type: `doc`,
            id: `audit-logs`,
          },
          items: [
            {
              type: `category`,
              label: `User logs`,
              link: {
                type: `doc`,
                id: `user-logs`,
              },
              items: [
                {
                  type: `doc`,
                  id: `user-log-data`,
                },
              ],
            },
            {
              type: `category`,
              label: `System logs`,
              link: {
                type: `doc`,
                id: `system-logs`,
              },
              items: [
                {
                  type: `doc`,
                  id: `system-log-data`,
                },
              ],
            },
          ],
        },
        {
          type: `doc`,
          id: `console-settings`,
        },
        {
          type: `category`,
          label: `License Information`,
          link: {
            type: `doc`,
            id: `license-information`,
          },
          items: [
            {
              type: `doc`,
              id: `xdr-data-retention`,
            },
          ],
        },
        {
          type: `category`,
          label: `Domain Verification`,
          link: {
            type: `doc`,
            id: `domain-verification`,
          },
          items: [
            {
              type: `doc`,
              id: `adding-managing-domains`,
            },
          ],
        },
      ],
    },
    {
      type: `category`,
      label: `Getting Help and Troubleshooting`,
      link: {
        type: `doc`,
        id: `getting-help-troubleshooting`,
      },
      items: [
        {
          type: `category`,
          label: `Help and Support`,
          link: {
            type: `doc`,
            id: `help-support`,
          },
          items: [
            {
              type: `doc`,
              id: `creating-support-case`,
            },
          ],
        },
        {
          type: `category`,
          label: `Self-Diagnosis`,
          link: {
            type: `doc`,
            id: `self-diagnosis`,
          },
          items: [
            {
              type: `category`,
              label: `Running diagnostic tests`,
              link: {
                type: `doc`,
                id: `running-diagnostic-tests`,
              },
              items: [
                {
                  type: `doc`,
                  id: `finding-endpoint-information`,
                },
              ],
            },
            {
              type: `doc`,
              id: `test-results-tab`,
            },
            {
              type: `category`,
              label: `XDR Endpoint Checker`,
              link: {
                type: `doc`,
                id: `xdr-endpoint-checker`,
              },
              items: [
                {
                  type: `doc`,
                  id: `use-xdr-checker-browser`,
                },
                {
                  type: `doc`,
                  id: `use-xdr-checker-cli`,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
